# Generated by Django 4.2.10 on 2024-05-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_username', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('search_type', models.CharField(max_length=20)),
                ('search_query', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
